variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE

stages:
    - deploy
    - test

deploy:
    image: python:3.6
    stage: build
    before_script:
        - python3 -m pip install --user --upgrade setuptools wheel twine
    script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/*
    only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    environment:
        name: dev
    
test:
    image: python:3.6
    stage: test
    before_script:
        - python3 -m pip install --user --upgrade setuptools wheel twine
    script:
        python3 -m pip install cfd-reader
        python3 -c "import cfd-reader"
    only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
    environment:
        name: dev